/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Customer;
import Model.DeliveryPackage;
import Model.Product;

/**
 *
 *@author bhagy

 */
public class DisplayJPanel extends javax.swing.JPanel {

    private DeliveryPackage delPackage;

   
    public DisplayJPanel() {
        initComponents();
        
    }

    DisplayJPanel(DeliveryPackage deliveryPackage) {
        initComponents();
        
        this.delPackage = deliveryPackage;
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        packageIdDisplay = new javax.swing.JTextField();
        packageWtDisplay = new javax.swing.JTextField();
        custIdDisplay = new javax.swing.JTextField();
        productIdDisplay = new javax.swing.JTextField();
        productNameDisplay = new javax.swing.JTextField();
        productPriceDisplay = new javax.swing.JTextField();
        custNameDisplay = new javax.swing.JTextField();
        custIdDisplayLabel = new javax.swing.JLabel();
        packageIdDisplayLabel = new javax.swing.JLabel();
        packageWeightDisplayLabel = new javax.swing.JLabel();
        prodIdDisplayLabel = new javax.swing.JLabel();
        prodNameDisplayLabel = new javax.swing.JLabel();
        prodPriceDisplayLabel = new javax.swing.JLabel();
        custNameDisplayLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(packageIdDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 130, 30));
        add(packageWtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 130, 30));
        add(custIdDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 130, 30));
        add(productIdDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 130, 30));
        add(productNameDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 130, 30));
        add(productPriceDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 130, 30));
        add(custNameDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 130, 30));

        custIdDisplayLabel.setText("ID");
        add(custIdDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, 20));

        packageIdDisplayLabel.setText("Package Id");
        add(packageIdDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        packageWeightDisplayLabel.setText("weight");
        add(packageWeightDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        prodIdDisplayLabel.setText("ProdId");
        add(prodIdDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 20));

        prodNameDisplayLabel.setText("ProdName");
        add(prodNameDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 20));

        prodPriceDisplayLabel.setText("ProdPrice");
        add(prodPriceDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 20));

        custNameDisplayLabel.setText("Customer name");
        add(custNameDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, 20));
    }// </editor-fold>//GEN-END:initComponents
    
    public void display() {
        packageIdDisplay.setText(String.valueOf(this.delPackage.getPackageId()));
        packageWtDisplay.setText(String.valueOf(this.delPackage.getPackageWeight()));
        
        Customer customer = this.delPackage.getCustomer();
        custIdDisplay.setText(String.valueOf(customer.getCustomerId()));
        custNameDisplay.setText(customer.getFullName());
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField custIdDisplay;
    private javax.swing.JLabel custIdDisplayLabel;
    private javax.swing.JTextField custNameDisplay;
    private javax.swing.JLabel custNameDisplayLabel;
    private javax.swing.JTextField packageIdDisplay;
    private javax.swing.JLabel packageIdDisplayLabel;
    private javax.swing.JLabel packageWeightDisplayLabel;
    private javax.swing.JTextField packageWtDisplay;
    private javax.swing.JLabel prodIdDisplayLabel;
    private javax.swing.JLabel prodNameDisplayLabel;
    private javax.swing.JLabel prodPriceDisplayLabel;
    private javax.swing.JTextField productIdDisplay;
    private javax.swing.JTextField productNameDisplay;
    private javax.swing.JTextField productPriceDisplay;
    // End of variables declaration//GEN-END:variables
}
