/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Address;
import Model.ContactInfo;
import Model.Student;
import javax.swing.JOptionPane;

/**
 *
 * @author bhagy
 */
public class HuskyCard extends javax.swing.JFrame {

    /**
     * Creates new form HuskyCard
     */
    private Student student;
    
    public HuskyCard() {
        initComponents();
        this.student = new Student();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        LableNUID = new javax.swing.JLabel();
        LabelFName = new javax.swing.JLabel();
        LabelLName = new javax.swing.JLabel();
        LabelCollegeName = new javax.swing.JLabel();
        LabelContactInfo = new javax.swing.JLabel();
        LabelPhone = new javax.swing.JLabel();
        LabelEmail = new javax.swing.JLabel();
        LabelCurrentAddress = new javax.swing.JLabel();
        NUID = new javax.swing.JTextField();
        FirstName = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        CollegeName = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        LabelStreetName = new javax.swing.JLabel();
        LabelAptNo = new javax.swing.JLabel();
        LabelCity = new javax.swing.JLabel();
        LabelZipCode = new javax.swing.JLabel();
        LabelContactInfoPersonal = new javax.swing.JLabel();
        LabelPhonePersonal = new javax.swing.JLabel();
        LabelEmailPersonal = new javax.swing.JLabel();
        pPhone = new javax.swing.JTextField();
        pEmail = new javax.swing.JTextField();
        StreetName = new javax.swing.JTextField();
        APTNo = new javax.swing.JTextField();
        City = new javax.swing.JTextField();
        Zip = new javax.swing.JTextField();
        LabelHeading = new javax.swing.JLabel();
        LabelPermanentAddress = new javax.swing.JLabel();
        LabelStreetNameP = new javax.swing.JLabel();
        LabelAPTNoP = new javax.swing.JLabel();
        LabelCityP = new javax.swing.JLabel();
        LabelZipCodeP = new javax.swing.JLabel();
        PStreetName = new javax.swing.JTextField();
        PAptNo = new javax.swing.JTextField();
        PCity = new javax.swing.JTextField();
        PZipCode = new javax.swing.JTextField();
        ViewButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        LabelDisplayMain = new javax.swing.JLabel();
        LabelDisplayFName = new javax.swing.JLabel();
        LabelLastName = new javax.swing.JLabel();
        LabelNuId = new javax.swing.JLabel();
        LabelCname = new javax.swing.JLabel();
        LabelOemail = new javax.swing.JLabel();
        LabelOPhone = new javax.swing.JLabel();
        LabelpEmail = new javax.swing.JLabel();
        LabelpPhone = new javax.swing.JLabel();
        LabelCStreetName = new javax.swing.JLabel();
        LabelCAptNo = new javax.swing.JLabel();
        LabelCCity = new javax.swing.JLabel();
        LabelcZip = new javax.swing.JLabel();
        LabelPStreetName = new javax.swing.JLabel();
        LabelpAptNo = new javax.swing.JLabel();
        LabelPCity = new javax.swing.JLabel();
        LabelPZip = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));

        LableNUID.setText("NUID");

        LabelFName.setText("FirstName");

        LabelLName.setText("LastName");

        LabelCollegeName.setText("CollegeName");

        LabelContactInfo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        LabelContactInfo.setText("Contact Information - Office");

        LabelPhone.setText("Phone");

        LabelEmail.setText("Email");

        LabelCurrentAddress.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        LabelCurrentAddress.setText("Current Address");

        NUID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUIDActionPerformed(evt);
            }
        });

        FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameActionPerformed(evt);
            }
        });

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });

        LabelStreetName.setText("Street Name");

        LabelAptNo.setText("APT No");

        LabelCity.setText("City");

        LabelZipCode.setText("ZipCode");

        LabelContactInfoPersonal.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        LabelContactInfoPersonal.setText("Contact Information - Personal");

        LabelPhonePersonal.setText("Phone");

        LabelEmailPersonal.setText("Email");

        LabelHeading.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        LabelHeading.setText("HUSKY CARD INFO");

        LabelPermanentAddress.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        LabelPermanentAddress.setText("Permanent Address");

        LabelStreetNameP.setText("Street Name");

        LabelAPTNoP.setText("APT No");

        LabelCityP.setText("City");

        LabelZipCodeP.setText("ZipCode");

        ViewButton.setText("VIEW INFO");
        ViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LabelContactInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelContactInfoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(LabelCurrentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(LabelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(LabelEmail)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(LabelEmailPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pEmail))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(LabelPhonePersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelStreetNameP, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelAPTNoP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelCityP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelZipCodeP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PStreetName)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(PZipCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(PCity, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PAptNo, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addComponent(LabelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelPermanentAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(ViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelCity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(StreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Zip, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                        .addComponent(City, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(APTNo, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LableNUID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(LabelLName)
                        .addComponent(LabelFName))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(LabelCollegeName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NUID)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CollegeName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addComponent(LastName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(FirstName, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(LabelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LableNUID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LabelFName)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(FirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LabelLName, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(LabelCollegeName)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(CollegeName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelContactInfoPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelContactInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPhone)
                    .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPhonePersonal)
                    .addComponent(pPhone))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelEmailPersonal)
                            .addComponent(pEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LabelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(29, 29, 29)
                .addComponent(LabelCurrentAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LabelStreetName)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(StreetName, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LabelAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(APTNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LabelCity)
                        .addGap(18, 18, 18)
                        .addComponent(LabelZipCode))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Zip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(LabelPermanentAddress)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelStreetNameP)
                    .addComponent(PStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAPTNoP)
                    .addComponent(PAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelCityP)
                    .addComponent(PCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelZipCodeP)
                    .addComponent(PZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewButton))
        );

        jSplitPane1.setLeftComponent(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 204, 255));

        LabelDisplayMain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelDisplayMain.setText("DISPLAY INFO");

        LabelDisplayFName.setText("First Name");

        LabelLastName.setText("Last Name");

        LabelNuId.setText("NUID ");

        LabelCname.setText("College Name");

        LabelOemail.setText("Office email");

        LabelOPhone.setText("Office Phone");

        LabelpEmail.setText("personal email");

        LabelpPhone.setText("personal phone");

        LabelCStreetName.setText("CStreetName");

        LabelCAptNo.setText("CAptNo");

        LabelCCity.setText("CCity");

        LabelcZip.setText("CZip");

        LabelPStreetName.setText("PStreetName");

        LabelpAptNo.setText("PAptNo");

        LabelPCity.setText("pCity");

        LabelPZip.setText("pZip");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(LabelDisplayFName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelDisplayMain))
                    .addComponent(LabelCname)
                    .addComponent(LabelCStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelcZip, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LabelOemail, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(LabelCCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelOPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelpPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(LabelLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LabelpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelpAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPCity, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPZip, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNuId, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDisplayMain)
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDisplayFName)
                    .addComponent(LabelLastName))
                .addGap(18, 18, 18)
                .addComponent(LabelNuId)
                .addGap(18, 18, 18)
                .addComponent(LabelCname)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelOemail)
                    .addComponent(LabelOPhone))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelpEmail)
                    .addComponent(LabelpPhone))
                .addGap(31, 31, 31)
                .addComponent(LabelCStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelCAptNo)
                .addGap(25, 25, 25)
                .addComponent(LabelCCity)
                .addGap(18, 18, 18)
                .addComponent(LabelcZip)
                .addGap(18, 18, 18)
                .addComponent(LabelPStreetName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelpAptNo)
                .addGap(18, 18, 18)
                .addComponent(LabelPCity)
                .addGap(18, 18, 18)
                .addComponent(LabelPZip)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel4);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NUIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUIDActionPerformed

    private void FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButtonActionPerformed
        // TODO add your handling code here:
        // Logic to view the student info:
        
        String fName = FirstName.getText();
        String lName = LastName.getText();
        String cName = CollegeName.getText();
        String nuid = NUID.getText();
        
        this.student.setfName(fName);
        this.student.setlName(lName);
        this.student.setCollegeName(cName);
        this.student.setNUID(Long.parseLong(nuid));
        
        Address currentAddress = this.student.getCurrentAddress();
        Address permAddress = this.student.getPermAddress();
        ContactInfo officeContact = this.student.getOfficeContact();
        ContactInfo personalContact = this.student.getPersonalContact();
   
        
        String oEmail = Email.getText();
        String perEmail = pEmail.getText();
        String oPhone = Phone.getText();
        String perPhone = pPhone.getText();
        
        String cStreetName = StreetName.getText();
        String cAptNo = APTNo.getText();
        String cCity = City.getText();
        String cZip = Zip.getText();
        
        String pStreetName = PStreetName.getText();
        String pAptNo = PAptNo.getText();
        String pCity = PCity.getText();
        String pZip = PZipCode.getText();
        
        currentAddress.setAptNumber(Integer.parseInt(cAptNo));
        currentAddress.setCity(cCity);
        currentAddress.setStreetName(cStreetName);
        currentAddress.setZipCode(Long.parseLong(cZip));
        
        permAddress.setAptNumber(Integer.parseInt(pAptNo));
        permAddress.setCity(pCity);
        permAddress.setStreetName(pStreetName);
        permAddress.setZipCode(Long.parseLong(pZip));
        
        
        officeContact.setEmail(oEmail);
        officeContact.setPhoneNumber(Long.parseLong(oPhone));
        
        personalContact.setEmail(perEmail);
        personalContact.setPhoneNumber(Long.parseLong(perPhone));
        
        
        JOptionPane.showMessageDialog(null, "Saved Successfully");
        
        display();
        
         
    }//GEN-LAST:event_ViewButtonActionPerformed
private void display()
    {
        Student obj2 = new Student();
        LabelDisplayFName.setText(this.student.getfName());
        LabelLName.setText(this.student.getlName());
        LabelNuId.setText((String.valueOf(this.student.getNUID())));
        LabelCname.setText(this.student.getCollegeName());
        
        LabelOPhone.setText((String.valueOf(this.student.getOfficeContact().getPhoneNumber())));
        LabelOemail.setText(this.student.getOfficeContact().getEmail());
        LabelpPhone.setText(String.valueOf(this.student.getPersonalContact().getPhoneNumber()));
        LabelpEmail.setText(this.student.getPersonalContact().getEmail());
        
        LabelCStreetName.setText(this.student.getCurrentAddress().getStreetName());
        LabelAptNo.setText(String.valueOf(this.student.getCurrentAddress().getAptNumber()));
        LabelCCity.setText(this.student.getCurrentAddress().getCity());
        LabelcZip.setText(String.valueOf(this.student.getCurrentAddress().getZipCode()));
        
        LabelPStreetName.setText(this.student.getPermAddress().getStreetName());
        LabelpAptNo.setText(String.valueOf(this.student.getPermAddress().getAptNumber()));
        LabelPCity.setText(this.student.getPermAddress().getCity());
        LabelPZip.setText(String.valueOf(this.student.getPermAddress().getZipCode()));
            
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HuskyCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HuskyCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HuskyCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HuskyCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HuskyCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField APTNo;
    private javax.swing.JTextField City;
    private javax.swing.JTextField CollegeName;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FirstName;
    private javax.swing.JLabel LabelAPTNoP;
    private javax.swing.JLabel LabelAptNo;
    private javax.swing.JLabel LabelCAptNo;
    private javax.swing.JLabel LabelCCity;
    private javax.swing.JLabel LabelCStreetName;
    private javax.swing.JLabel LabelCity;
    private javax.swing.JLabel LabelCityP;
    private javax.swing.JLabel LabelCname;
    private javax.swing.JLabel LabelCollegeName;
    private javax.swing.JLabel LabelContactInfo;
    private javax.swing.JLabel LabelContactInfoPersonal;
    private javax.swing.JLabel LabelCurrentAddress;
    private javax.swing.JLabel LabelDisplayFName;
    private javax.swing.JLabel LabelDisplayMain;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelEmailPersonal;
    private javax.swing.JLabel LabelFName;
    private javax.swing.JLabel LabelHeading;
    private javax.swing.JLabel LabelLName;
    private javax.swing.JLabel LabelLastName;
    private javax.swing.JLabel LabelNuId;
    private javax.swing.JLabel LabelOPhone;
    private javax.swing.JLabel LabelOemail;
    private javax.swing.JLabel LabelPCity;
    private javax.swing.JLabel LabelPStreetName;
    private javax.swing.JLabel LabelPZip;
    private javax.swing.JLabel LabelPermanentAddress;
    private javax.swing.JLabel LabelPhone;
    private javax.swing.JLabel LabelPhonePersonal;
    private javax.swing.JLabel LabelStreetName;
    private javax.swing.JLabel LabelStreetNameP;
    private javax.swing.JLabel LabelZipCode;
    private javax.swing.JLabel LabelZipCodeP;
    private javax.swing.JLabel LabelcZip;
    private javax.swing.JLabel LabelpAptNo;
    private javax.swing.JLabel LabelpEmail;
    private javax.swing.JLabel LabelpPhone;
    private javax.swing.JLabel LableNUID;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField NUID;
    private javax.swing.JTextField PAptNo;
    private javax.swing.JTextField PCity;
    private javax.swing.JTextField PStreetName;
    private javax.swing.JTextField PZipCode;
    private javax.swing.JTextField Phone;
    private javax.swing.JTextField StreetName;
    private javax.swing.JButton ViewButton;
    private javax.swing.JTextField Zip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField pEmail;
    private javax.swing.JTextField pPhone;
    // End of variables declaration//GEN-END:variables
}
