/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Customer;
import Model.DeliveryPackage;
import Model.Product;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Bhagyashri Chavan
 */
public class UpdateJPanel extends javax.swing.JPanel {

    private DeliveryPackage delPackage;
    private Product productViewed;

    /**
     * Creates new form EditJPanel
     */
    public UpdateJPanel() {
        initComponents();
    }

    UpdateJPanel(DeliveryPackage deliveryPackage) {
        initComponents();

        this.delPackage = deliveryPackage;

        displayProductList();
        
        displayPackageDetails();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        packageIdUpdate = new javax.swing.JTextField();
        packageWtUpdate = new javax.swing.JTextField();
        custIdUpdate = new javax.swing.JTextField();
        productIdUpdate = new javax.swing.JTextField();
        productNameUpdate = new javax.swing.JTextField();
        productPriceUpdate = new javax.swing.JTextField();
        custNameUpdate = new javax.swing.JTextField();
        custIdLabel = new javax.swing.JLabel();
        packageIdLabel = new javax.swing.JLabel();
        packageWeightLabel = new javax.swing.JLabel();
        prodIdLabel = new javax.swing.JLabel();
        prodNameLabel = new javax.swing.JLabel();
        prodPriceLabel = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnUpdateProduct = new javax.swing.JButton();
        prodCombo = new javax.swing.JComboBox();
        btnShow = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(packageIdUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 130, 30));
        add(packageWtUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 130, 30));
        add(custIdUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 130, 30));
        add(productIdUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 130, 30));
        add(productNameUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 130, 30));
        add(productPriceUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 130, 30));
        add(custNameUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 130, 30));

        custIdLabel.setText("ID");
        add(custIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, 20));

        packageIdLabel.setText("Package Id");
        add(packageIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        packageWeightLabel.setText("weight");
        add(packageWeightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        prodIdLabel.setText("ProdId");
        add(prodIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 20));

        prodNameLabel.setText("ProdName");
        add(prodNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, 20));

        prodPriceLabel.setText("ProdPrice");
        add(prodPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, 20));

        customerNameLabel.setText("Customer name");
        add(customerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, 20));

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 90, 20));

        btnUpdateProduct.setText("UPDATE PRODUCT");
        btnUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProductActionPerformed(evt);
            }
        });
        add(btnUpdateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, -1));

        add(prodCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 150, 30));

        btnShow.setText("SHOW");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        add(btnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 80, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        // get the data
        String id = packageIdUpdate.getText();
        String weight = packageWtUpdate.getText();
//        String productId = productId1.getText();
//        String productName = productName1.getText();
//        String productPrice = productPrice1.getText();
        String customerId = custIdUpdate.getText();
        String customername = custNameUpdate.getText();

        // store the data
        this.delPackage.setPackageId(Integer.valueOf(id));
        this.delPackage.setPackageWeight(Double.valueOf(weight));

        Customer customer = this.delPackage.getCustomer();
        customer.setCustomerId(Integer.valueOf(customerId));
        customer.setFullName(customername);

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProductActionPerformed
        // TODO add your handling code here:
        
        
        // update the product in the list
        this.productViewed.setProductName(productNameUpdate.getText());
        this.productViewed.setPrice(Double.valueOf(productPriceUpdate.getText()));
        
        
        
        // Update the Product Selected
    }//GEN-LAST:event_btnUpdateProductActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:

        // to disable the field
        productIdUpdate.setEnabled(false);
        
        int pid = (int) prodCombo.getSelectedItem();

        // find the product in the arraylsit
        Product prod = this.delPackage.findProduct(pid);
         this.productViewed = prod;
        // display the product content

        if (!prod.equals(null)) {
            productIdUpdate.setText(String.valueOf(pid));
            productNameUpdate.setText(prod.getProductName());
            productPriceUpdate.setText(String.valueOf(prod.getPrice()));
        } else {
            JOptionPane.showMessageDialog(null, "Product not found");
        }

    }//GEN-LAST:event_btnShowActionPerformed

    public void displayProductList() {

        for (Product p : this.delPackage.getProductList()) {
            prodCombo.addItem(p.getProductId());
        }

    }

    public void displayPackageDetails() {
        packageIdUpdate.setText(String.valueOf(this.delPackage.getPackageId()));
        packageWtUpdate.setText(String.valueOf(this.delPackage.getPackageWeight()));

        Customer customer = this.delPackage.getCustomer();
        custIdUpdate.setText(String.valueOf(customer.getCustomerId()));
        custNameUpdate.setText(customer.getFullName());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateProduct;
    private javax.swing.JLabel custIdLabel;
    private javax.swing.JTextField custIdUpdate;
    private javax.swing.JTextField custNameUpdate;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JLabel packageIdLabel;
    private javax.swing.JTextField packageIdUpdate;
    private javax.swing.JLabel packageWeightLabel;
    private javax.swing.JTextField packageWtUpdate;
    private javax.swing.JComboBox prodCombo;
    private javax.swing.JLabel prodIdLabel;
    private javax.swing.JLabel prodNameLabel;
    private javax.swing.JLabel prodPriceLabel;
    private javax.swing.JTextField productIdUpdate;
    private javax.swing.JTextField productNameUpdate;
    private javax.swing.JTextField productPriceUpdate;
    // End of variables declaration//GEN-END:variables
}
